name: 'Test'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to check out the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: 'Install Node'
        uses: pnpm/setup-node@v2
        with:
          version: 7
      - name: 'Install Deps'
        run: pnpm install --frozen-lockfile
      - name: 'Test'
        run: npx vitest --coverage
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses:  davelosert/vitest-coverage-report-action@v2